version: 2
updates:
  - package-ecosystem: npm
    directory: /app
    schedule:
      interval: weekly
    groups:
      frontend-dependencies:
        patterns:
          - '*'

  - package-ecosystem: cargo
    directory: /app/src-tauri
    schedule:
      interval: weekly
    groups:
      rust-dependencies:
        patterns:
          - '*'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      workflow-actions:
        patterns:
          - '*'
