import { create } from 'zustand'
import { invoke } from '@tauri-apps/api/core'

export type Skill = {
  id: string
  name: string
  description: string
  prompt_template: string
  trigger_pattern: string | null
  run_mode: string
  version: number
  usage_count: number
  success_count: number
  fail_count: number
  avg_quality: number
  auto_generated: boolean
  parent_skill_id: string | null
  source_task_ids: string | null
  created_at: string
  updated_at: string
}

export type SkillAutoGenResult = {
  generated: boolean
  skill_name: string | null
  reason: string
}

export type LearningOutcome = {
  id: string
  session_id: string | null
  task_id: string | null
  outcome_type: string
  description: string
  learned_pattern: string | null
  confidence: number
  applied_count: number
  created_at: string
}

type SkillState = {
  skills: Skill[]
  learnings: LearningOutcome[]
  loading: boolean
  error: string | null

  loadSkills: (limit?: number) => Promise<void>
  upsertSkill: (s: {
    id: string; name: string; description: string; promptTemplate: string
    triggerPattern?: string; runMode?: string; autoGenerated?: boolean
    parentSkillId?: string; sourceTaskIds?: string
  }) => Promise<void>
  deleteSkill: (id: string) => Promise<void>
  recordUsage: (skillId: string, success: boolean, quality: number) => Promise<void>
  improveSkill: (skillId: string, newPromptTemplate: string, reason: string) => Promise<void>
  matchSkill: (input: string) => Promise<Skill | null>
  autoGenerate: (taskTitle: string, taskPrompt: string, taskStepsSummary: string, taskOutcome: string) => Promise<SkillAutoGenResult>

  loadLearnings: (limit?: number) => Promise<void>
  addLearning: (l: {
    sessionId?: string; taskId?: string; outcomeType: string; description: string
    learnedPattern?: string; confidence?: number
  }) => Promise<void>
}

export const useSkillStore = create<SkillState>()((set) => ({
  skills: [],
  learnings: [],
  loading: false,
  error: null,

  loadSkills: async (limit = 200) => {
    set({ loading: true, error: null })
    try {
      const skills = await invoke<Skill[]>('skill_list', { limit })
      set({ skills, loading: false })
    } catch (e) {
      set({ error: String(e), loading: false })
    }
  },

  upsertSkill: async (s) => {
    try {
      await invoke('skill_upsert', {
        id: s.id,
        name: s.name,
        description: s.description,
        promptTemplate: s.promptTemplate,
        triggerPattern: s.triggerPattern ?? null,
        runMode: s.runMode ?? 'execute',
        autoGenerated: s.autoGenerated ?? false,
        parentSkillId: s.parentSkillId ?? null,
        sourceTaskIds: s.sourceTaskIds ?? null,
      })
    } catch (e) {
      set({ error: String(e) })
    }
  },

  deleteSkill: async (id) => {
    try {
      await invoke('skill_delete', { id })
      set((s) => ({ skills: s.skills.filter((sk) => sk.id !== id) }))
    } catch (e) {
      set({ error: String(e) })
    }
  },

  recordUsage: async (skillId, success, quality) => {
    try {
      await invoke('skill_record_usage', { id: skillId, success, quality })
    } catch (e) {
      set({ error: String(e) })
    }
  },

  improveSkill: async (skillId, newPromptTemplate, reason) => {
    try {
      await invoke('skill_improve', { skillId, newPromptTemplate, reason })
    } catch (e) {
      set({ error: String(e) })
    }
  },

  matchSkill: async (input) => {
    try {
      const result = await invoke<Skill | null>('skill_match', { userInput: input })
      return result
    } catch {
      return null
    }
  },

  autoGenerate: async (taskTitle, taskPrompt, taskStepsSummary, taskOutcome) => {
    const result = await invoke<SkillAutoGenResult>('skill_auto_generate', {
      taskTitle,
      taskPrompt,
      taskStepsSummary,
      taskOutcome,
    })
    return result
  },

  loadLearnings: async (limit = 100) => {
    set({ loading: true })
    try {
      const learnings = await invoke<LearningOutcome[]>('learning_list', { limit })
      set({ learnings, loading: false })
    } catch (e) {
      set({ error: String(e), loading: false })
    }
  },

  addLearning: async (l) => {
    const id = `learn-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`
    try {
      await invoke('learning_upsert', {
        id,
        sessionId: l.sessionId ?? null,
        taskId: l.taskId ?? null,
        outcomeType: l.outcomeType,
        description: l.description,
        learnedPattern: l.learnedPattern ?? null,
        confidence: l.confidence ?? 1.0,
      })
    } catch (e) {
      set({ error: String(e) })
    }
  },
}))
